version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: '${POSTGRES_USERNAME}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
